# Generated by Django 5.0.1 on 2024-01-17 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabs', '0003_collab_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollabImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('is_main', models.BooleanField(default=False)),
                ('collab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='collabs.collab')),
            ],
        ),
    ]
