# Generated by Django 5.0.1 on 2024-01-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabs', '0005_remove_collab_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collabimage',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
